name: deploy

on:
  push:
    branches:
      - dokku

jobs:
  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      meta: ${{ steps.meta.outputs.json }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Get current version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "VERSION_COMMIT = \"$(git rev-parse --short=8 origin/v2)\"" > app/_version.py
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/microblogpub
          tags: |
            type=sha,prefix=sha-,format=short
            type=raw,value=${{ steps.version.outputs.tag }}
            type=raw,value=latest
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dokku:
    name: Deploy to dokku host
    needs: docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Build app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: dokku
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git:from-image ${{ secrets.DOKKU_APP }} ${{ fromJson(needs.docker.outputs.meta).tags[2] }}
